// Prelude — Nintendo Switch homebrew for the Nextendo Network.
// Copyright (C) 2026 Nextendo Network
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU Affero General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
// PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License along
// with this program. If not, see <https://www.gnu.org/licenses/>.

// Contents of the Atmosphere DNS-MITM hosts files (sysmmc.txt + emummc.txt), generated by the app.
// Atmosphere rule: the LAST matching line wins ('*' = 0+ characters, '%' = lp1).
// nncs1/nncs2 need TWO DISTINCT IPs, or Pia dedups the 2nd probe -> NAT never completes -> 2618-201.
// WARNING: the literal below is written to the SD card verbatim, '#' comments included.
#ifndef NEXTENDO_HOSTS_H
#define NEXTENDO_HOSTS_H

#include "nextendo_config.h"

// Dynamically allocated — the caller must free() it.
char *nextendo_hosts_build(const char *ip);

// Signature of OUR hosts files: recognises them without depending on the current IP.
#define NEXTENDO_HOSTS_HEADER_MARK "NEXTENDO NETWORK - Atmosphere DNS-MITM"

#define NEXTENDO_HOSTS_SYSMMC "sdmc:/atmosphere/hosts/sysmmc.txt"
#define NEXTENDO_HOSTS_EMUMMC "sdmc:/atmosphere/hosts/emummc.txt"
#define NEXTENDO_HOSTS_DIR    "sdmc:/atmosphere/hosts"
#define NEXTENDO_SETTINGS_INI "sdmc:/atmosphere/config/system_settings.ini"

#endif // NEXTENDO_HOSTS_H
